### ISSUE TITLE
[FEATURE REQUEST] Show both screens side by side, or on top of each other, or just have seperate RCA connections for both screens? Either three would be fine, to be honest, I don't really need all three for what I am using this for.

### ISSUE THREAD

**Issue by 6100m** [LostNintendoHistory/Lost-NDS-TV#1]
Love this project, but the only feature that's not here yet that I need is the one I mentioned in the title because I want this on a LCD. Touchscreen I'm not asking for just yet, but I have been researching the touchscreen signals on and off, and I even know the exact spot they are on the board. Contact me at myhacknull@gmail.com if you want to discuss the touchscreen stuff further haha.

Honestly I'd go for either three of the options, but is it even possible though?

**Comment by pedro-javierf** [comment]
Unfortunately those options are not supported natively by the DS Lite SoC, so there's nothing we can do. Such a thing would require extra hardware, like a capture card hooked to each of the 2 lcd's flex.

**Comment by tomrow** [comment]
Probably out of scope, but I had a theory that if the DS can cope with it, one could use a suitably fast microcontroller or something to switch screen modes every 60th of a second, and use that to generate a 480 line signal with both screens at 30 frames per second.

**Comment by ItsRogueRen** [comment]
> Unfortunately those options are not supported natively by the DS Lite SoC, so there's nothing we can do. Such a thing would require extra hardware, like a capture card hooked to each of the 2 lcd's flex.

what if both flex cables went to 1 PCB that combined them into a single 512x192 video rather than two 256x192 videos? The board would have to be more expensive and maybe have something like an audrino (or similar device). Just an idea though.

**Comment by ylorant** [comment]
> what if both flex cables went to 1 PCB that combined them into a single 512x192 video rather than two 256x192 videos? The board would have to be more expensive and maybe have something like an audrino (or similar device). Just an idea though.

What you are describing is basically the actual DS capture card that already exists. Uses only 1 flex though, as the console (at least the DS Tank, which the capture card is made for) sends the two screens on it (top on rising clock, bottom on falling clock iirc).

**Comment by ItsRogueRen** [comment]
> > what if both flex cables went to 1 PCB that combined them into a single 512x192 video rather than two 256x192 videos? The board would have to be more expensive and maybe have something like an audrino (or similar device). Just an idea though.
> 
> What you are describing is basically the actual DS capture card that already exists. Uses only 1 flex though, as the console (at least the DS Tank, which the capture card is made for) sends the two screens on it (top on rising clock, bottom on falling clock iirc).

As far as I know those are no longer being made though, Loopy hasn't made any capture cards is years.

**Comment by ylorant** [comment]
> As far as I know those are no longer being made though, Loopy hasn't made any capture cards in years.

They're in stock right now.
