### ISSUE TITLE
2-layer PCB version

### ISSUE THREAD

**Issue by lpla** [LostNintendoHistory/Lost-NDS-TV#2]
Hi. I am interested in ordering the PCB through a service like OSHPark or JLCPCB.

I noticed that the price is higher than other PCBs because gerbers from this project contain 4 layers. Is it really necessary to use 4 layers instead of 2?

Cheers and thank you for publishing all this content!

**Comment by pedro-javierf** [comment]
Hello. Yes, 4 layers are necessary to reduce noise in the data lines. Nonetheless, it should not be more expensive than 2 layers. At least it hasn't been like that in our experience and orders so far.  Check this: https://twitter.com/Nitehack/status/1372637386035843083?s=20

**Comment by lpla** [comment]
Oh, you are right. Seems like only OSHPark is more expensive using 4 layers. I will order it through JLCPCB then. Thank you!
